{% set version = "0.5.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hms
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/hms_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/hms/hms_{{ version }}.tar.gz
  sha256: d445c98c36b224e73c76dd4fc2a700e0b1abf0ade3d8ac8ac96c12fb946e4440

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-pkgconfig
    - r-rlang
    - r-vctrs >=0.2.0
  run:
    - r-base
    - r-pkgconfig
    - r-rlang
    - r-vctrs >=0.2.0

test:
  commands:
    - $R -e "library('hms')"           # [not win]
    - "\"%R%\" -e \"library('hms')\""  # [win]

about:
  home: https://github.com/tidyverse/hms
  license: GPL-3
  summary: Implements an S3 class for storing and formatting time-of-day values, based on the
    'difftime' class.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: hms
# Title: Pretty Time of Day
# Date: 2019-07-09
# Version: 0.5.0
# Authors@R: c( person("Kirill", "Muller", role = c("aut", "cre"), email = "krlmlr+r@mailbox.org"), person("The R Consortium", role = "fnd"), person("RStudio", role = "fnd") )
# Description: Implements an S3 class for storing and formatting time-of-day values, based on the 'difftime' class.
# Imports: methods, pkgconfig, rlang, vctrs (>= 0.2.0)
# Suggests: crayon, lubridate, pillar (>= 1.1.0), testthat
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# URL: https://github.com/tidyverse/hms
# BugReports: https://github.com/tidyverse/hms/issues
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-07-09 09:29:38 UTC; kirill
# Author: Kirill Muller [aut, cre], The R Consortium [fnd], RStudio [fnd]
# Maintainer: Kirill Muller <krlmlr+r@mailbox.org>
# Repository: CRAN
# Date/Publication: 2019-07-09 10:50:03 UTC
