{% set version = "0.5.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hms
  version: {{ version|replace("-", "_") }}

source:
  fn: hms_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/hms_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/hms/hms_{{ version }}.tar.gz
  sha256: a87872665c3bf3901f597d78c152e7805f7129e4dbe27397051de4cf1a76561b

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-pkgconfig
    - r-rlang
  run:
    - r-base
    - r-pkgconfig
    - r-rlang

test:
  commands:
    - $R -e "library('hms')"           # [not win]
    - "\"%R%\" -e \"library('hms')\""  # [win]

about:
  home: https://github.com/tidyverse/hms
  license: GPL-3
  summary: Implements an S3 class for storing and formatting time-of-day values, based on the
    'difftime' class.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
