appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: s9Mj6lYSDD9yMcUyP1cXLiTm47Q3ebyAxD+1AZEoM50dMkXs/iDoADwj0F7Kgi0rLazSYtE4uisodsiFCYllE5cyC6YO2WPBXlF0/5VVquQ9siEOtoRm2ypPxoLOUc8YFZ52pA05UAPdRQ/Jh4PmStMhBxA3+mR9Jx76KMo33E0pewXC/5ctgwoS19YrcbrxQT0eLpsSH7DDOmh+KFUXY3F+qo7OlqA9DEl5TVdC1/mQX+GwKTfFBZ03e9IJ7Mooiz6PneId08HlRFxAqPno1qRX8vco95Yf0fBDw8/WGQEhfsl3DP+4rm0km+pmFe+JqGmNa/IJESBnfdRjEVn08/Vvc6zj06iQG3b3SBmAgbSKs7W2s4gM97iMEkQil8LyHPFzRG8j8Skn6vVLUA1eZcyKZgKIFj7MLMd+RGtelQFxnUp0x/cnIqZ2h1cSJdxGSlK1uYJBkQlYpr9DfAdQ0Cyuu2Wy297wTOgGdK/9QKCnKdWDAIObiM1fZiUIuta0EFjXHG9kxyAeEkKnmcKS3gAKBl8EXUNpjf36YLydRwXyAkdOyBEf0MAMC6xAtt4Is7je7LNt/TTU6eXOBpJ03bCnejpqYMCaZxKXieaMovuITnGpziwcn6gvA15CFaxHmUhaRRKmZbu+lplfCgrfI0naYgLb6OWLnJzi3wmDu6U=}
bot:
  automerge: true
